-- Fix store_status for multi-project support.
--
-- The previous primary key was store_status_pkey = primary key (store_id),
-- which prevents two projects from tracking the same store_id independently.
-- This migration preserves every store_status row and changes only key
-- enforcement to primary key (project_id, store_id).

create table if not exists public.store_status_pk_migration_audit_20260608 (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  check_name text not null,
  project_id text,
  store_id text,
  row_count integer,
  row_payload jsonb
);

comment on table public.store_status_pk_migration_audit_20260608 is
  'Audit snapshot created before migrating public.store_status from store_id primary key to project_id/store_id primary key.';

do $$
begin
  if to_regclass('public.store_status') is null then
    raise exception 'store_status composite primary key migration blocked: public.store_status does not exist.';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'store_status'
      and column_name = 'project_id'
  ) then
    raise exception 'store_status composite primary key migration blocked: public.store_status.project_id does not exist.';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'store_status'
      and column_name = 'store_id'
  ) then
    raise exception 'store_status composite primary key migration blocked: public.store_status.store_id does not exist.';
  end if;
end $$;

-- Keep a JSONB copy of every current row so existing and future columns are
-- captured without needing this migration to know the full table shape.
insert into public.store_status_pk_migration_audit_20260608 (
  check_name,
  project_id,
  store_id,
  row_payload
)
select
  'pre_migration_snapshot',
  ss.project_id::text,
  ss.store_id::text,
  to_jsonb(ss)
from public.store_status ss;

-- Record duplicate groups for inspection. If this migration is run inside a
-- transactional migration runner and the migration fails, these audit inserts
-- may roll back with the migration; the exception below also includes the
-- duplicate-inspection query to run manually.
insert into public.store_status_pk_migration_audit_20260608 (
  check_name,
  project_id,
  store_id,
  row_count
)
select
  'duplicate_project_store_key',
  grouped.project_id::text,
  grouped.store_id::text,
  grouped.row_count::integer
from (
  select project_id, store_id, count(*) as row_count
  from public.store_status
  group by project_id, store_id
  having count(*) > 1
) grouped;

do $$
declare
  duplicate_group_count bigint;
  duplicate_examples text;
  null_project_count bigint;
  null_store_count bigint;
begin
  select count(*)
  into null_project_count
  from public.store_status
  where project_id is null;

  if null_project_count > 0 then
    raise exception
      'store_status composite primary key migration blocked: % row(s) have null project_id. Assign the correct project_id before applying primary key (project_id, store_id).',
      null_project_count;
  end if;

  select count(*)
  into null_store_count
  from public.store_status
  where store_id is null;

  if null_store_count > 0 then
    raise exception
      'store_status composite primary key migration blocked: % row(s) have null store_id. Correct these rows before applying primary key (project_id, store_id).',
      null_store_count;
  end if;

  select count(*)
  into duplicate_group_count
  from (
    select project_id, store_id
    from public.store_status
    group by project_id, store_id
    having count(*) > 1
  ) duplicates;

  if duplicate_group_count > 0 then
    select string_agg(
      format('(%s, %s) has %s rows', project_id, store_id, row_count),
      '; '
    )
    into duplicate_examples
    from (
      select project_id::text, store_id::text, count(*) as row_count
      from public.store_status
      group by project_id, store_id
      having count(*) > 1
      order by project_id::text, store_id::text
      limit 10
    ) examples;

    raise exception
      'store_status composite primary key migration blocked: found % duplicate project_id/store_id group(s). Examples: %. Inspect with: select project_id, store_id, count(*) from public.store_status group by project_id, store_id having count(*) > 1 order by project_id, store_id;',
      duplicate_group_count,
      coalesce(duplicate_examples, '(none)');
  end if;
end $$;

-- Enforce the non-null side of the new composite key after the no-data-loss
-- preflight has confirmed that no existing rows need repair.
alter table public.store_status
  alter column project_id set not null,
  alter column store_id set not null;

do $$
declare
  existing_pk_name text;
  existing_pk_columns text[];
begin
  select
    c.conname,
    array_agg(a.attname order by keys.ordinality)
  into existing_pk_name, existing_pk_columns
  from pg_constraint c
  join unnest(c.conkey) with ordinality as keys(attnum, ordinality) on true
  join pg_attribute a
    on a.attrelid = c.conrelid
   and a.attnum = keys.attnum
  where c.conrelid = 'public.store_status'::regclass
    and c.contype = 'p'
  group by c.conname;

  if existing_pk_name is null then
    return;
  end if;

  if existing_pk_columns = array['project_id', 'store_id']::text[] then
    return;
  end if;

  -- Drop the old single-project key regardless of its generated name; the
  -- known production name is store_status_pkey.
  if existing_pk_columns = array['store_id']::text[] then
    execute format('alter table public.store_status drop constraint %I', existing_pk_name);
    return;
  end if;

  raise exception
    'store_status composite primary key migration blocked: unexpected existing primary key % on columns %. Review before replacing it.',
    existing_pk_name,
    existing_pk_columns;
end $$;

do $$
declare
  existing_pk_name text;
  existing_pk_columns text[];
begin
  select
    c.conname,
    array_agg(a.attname order by keys.ordinality)
  into existing_pk_name, existing_pk_columns
  from pg_constraint c
  join unnest(c.conkey) with ordinality as keys(attnum, ordinality) on true
  join pg_attribute a
    on a.attrelid = c.conrelid
   and a.attnum = keys.attnum
  where c.conrelid = 'public.store_status'::regclass
    and c.contype = 'p'
  group by c.conname;

  if existing_pk_name is null then
    alter table public.store_status
      add constraint store_status_pkey primary key (project_id, store_id);
    return;
  end if;

  if existing_pk_columns = array['project_id', 'store_id']::text[] then
    return;
  end if;

  raise exception
    'store_status composite primary key migration blocked: primary key % still exists on columns %.',
    existing_pk_name,
    existing_pk_columns;
end $$;

do $$
declare
  existing_pk_name text;
begin
  select c.conname
  into existing_pk_name
  from pg_constraint c
  where c.conrelid = 'public.store_status'::regclass
    and c.contype = 'p';

  if existing_pk_name is null then
    raise exception 'store_status composite primary key migration blocked: primary key was not created.';
  end if;

  execute format(
    'comment on constraint %I on public.store_status is %L',
    existing_pk_name,
    'Composite key scoped by project so the same store_id can have independent status rows in different projects.'
  );
end $$;
